# -*- coding: utf-8 -*-
"""cifraCesar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Wkp0-OoQJi4-EAJ96-9uhBMyb4inho5
"""

def cifracesar (texto, cave) :
  resultado = ""
  # iterando o texto
  for i in range (len(texto)):
    char = texto [i]
    # letras maiusculas
    if char. isupper():
      resultado += chr((ord(char) + chave - 65) % 26 + 65)
    # letras minusculas
    if char.islower():
      resultado += chr((ord(char) + chave - 97) % 26 + 97)
    # outros caracteres
    else:
      resultado += char
  return resultado

# exemplo
meuTexto = "Nathalia!"
chave = 4
textoCifrado = cifracesar (meuTexto, chave)

print("Texto original:", meuTexto)
print( "Texto Cifrado: ", textoCifrado)