# -*- coding: utf-8 -*-
"""semana0502_sha256.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-Wse0yMH4AM4nEADnobSNYpA0-UIKY6
"""

"""
Uma função de hash
"""
import hashlib

def hash_function(data):
  sha256 = hashlib.sha256()
  sha256.update(data. encode('utf-8' ))

# Retorna um Hash em formato Hexadecimal
  return sha256.hexdigest()

# Chamada:
data = "Exemplo de data"
hash_value = hash_function (data)
print(f"Hash: ", hash_value)