# -*- coding: utf-8 -*-
"""semana0501_nAleatorio.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151TroIBJXV8NbADgf7tI2R6k5sBylqkq
"""

"""
Geração de números aleatórios criptograficamente seguros
"""
import os

def generate_random_bytes(lenght):
#Gerar
#Parametri leght, numeri de bytes
#Retornar um numero aleatorio em formato hexadecimal
  return os. urandom (lenght).hex()

#Exemplo de uso
random_valeu = generate_random_bytes(16)
# 16 bytes aleatorios
print(f"Numero aleatorio: ", random_valeu)